name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - pycdfpp
  - matplotlib
  - numpy
  - ipympl
  - requests
  - xarray
  - PyYAML
  - tqdm
  - astropy
  - scipy
  - scikit-learn
  - pip:
    - https://sciqlop.lpp.polytechnique.fr/data/software/speasy-1.7.0-py3-none-any.whl
    - diskcache 
    - appdirs 
    - pyistp 
    - astroquery
